
#' @docType package
#' @name laraReport
#' @title A library for reporting data generated by lab automation systems
#' @details A library for reporting data generated by lab automation systems
#' @note date: 150601
#' @note last modification: 
#' 
#' @author mark doerr \email{mark.doerr@@uni-greifswald.de},
#'   and \email{mark@@ismeralda.org}

NULL
